//= require site/zmanim

assertTimeEqual = (assert, actual, expected) ->
  assert.equal actual.format("YYYY-MM-DD hh:mm:ss A"), expected.format("YYYY-MM-DD hh:mm:ss A")

zmanimTest = ->
  date = new Date(2016,4,3)
  boston = { latitude: 42.3601, longitude: -71.0589}
  QUnit.test "Zmanim test for #{date} in Boston", (assert) ->
    actual = new Zmanim(date, boston)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamDegrees(0), moment(date).hour(4).minute(0).second(21)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamDegrees(1), moment(date).hour(5).minute(27).second(21)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamDegrees(2), moment(date).hour(6).minute(54).second(20)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamDegrees(3), moment(date).hour(8).minute(21).second(19)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamDegrees(4), moment(date).hour(9).minute(48).second(19)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamDegrees(5), moment(date).hour(11).minute(15).second(18)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamDegrees(6), moment(date).hour(12).minute(42).second(17)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamDegrees(7), moment(date).hour(14).minute(9).second(17)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamDegrees(8), moment(date).hour(15).minute(36).second(16)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamDegrees(9), moment(date).hour(17).minute(3).second(15)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamDegrees(10), moment(date).hour(18).minute(30).second(15)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamDegrees(11), moment(date).hour(19).minute(57).second(14)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamDegrees(12), moment(date).hour(21).minute(24).second(14)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamFixedMinutes(0), moment(date).hour(4).minute(25).second(22)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamFixedMinutes(1), moment(date).hour(5).minute(48).second(11)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamFixedMinutes(2), moment(date).hour(7).minute(11).second(0)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamFixedMinutes(3), moment(date).hour(8).minute(33).second(50)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamFixedMinutes(4), moment(date).hour(9).minute(56).second(39)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamFixedMinutes(5), moment(date).hour(11).minute(19).second(28)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamFixedMinutes(6), moment(date).hour(12).minute(42).second(17)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamFixedMinutes(7), moment(date).hour(14).minute(5).second(7)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamFixedMinutes(8), moment(date).hour(15).minute(27).second(56)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamFixedMinutes(9), moment(date).hour(16).minute(50).second(45)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamFixedMinutes(10), moment(date).hour(18).minute(13).second(35)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamFixedMinutes(11), moment(date).hour(19).minute(36).second(24)
    assertTimeEqual assert, actual.shaaZemaniMagenAbrahamFixedMinutes(12), moment(date).hour(20).minute(59).second(13)
    assertTimeEqual assert, actual.shaaZemaniMagenAbraham(0), moment(date).hour(4).minute(0).second(21)
    assertTimeEqual assert, actual.shaaZemaniMagenAbraham(1), moment(date).hour(5).minute(27).second(21)
    assertTimeEqual assert, actual.shaaZemaniMagenAbraham(2), moment(date).hour(6).minute(54).second(20)
    assertTimeEqual assert, actual.shaaZemaniMagenAbraham(3), moment(date).hour(8).minute(21).second(19)
    assertTimeEqual assert, actual.shaaZemaniMagenAbraham(4), moment(date).hour(9).minute(48).second(19)
    assertTimeEqual assert, actual.shaaZemaniMagenAbraham(5), moment(date).hour(11).minute(15).second(18)
    assertTimeEqual assert, actual.shaaZemaniMagenAbraham(6), moment(date).hour(12).minute(42).second(17)
    assertTimeEqual assert, actual.shaaZemaniMagenAbraham(7), moment(date).hour(14).minute(5).second(7)
    assertTimeEqual assert, actual.shaaZemaniMagenAbraham(8), moment(date).hour(15).minute(27).second(56)
    assertTimeEqual assert, actual.shaaZemaniMagenAbraham(9), moment(date).hour(16).minute(50).second(45)
    assertTimeEqual assert, actual.shaaZemaniMagenAbraham(10), moment(date).hour(18).minute(13).second(35)
    assertTimeEqual assert, actual.shaaZemaniMagenAbraham(11), moment(date).hour(19).minute(36).second(24)
    assertTimeEqual assert, actual.shaaZemaniMagenAbraham(12), moment(date).hour(20).minute(59).second(13)
    assertTimeEqual assert, actual.shaaZemaniGra(0), moment(date).hour(5).minute(37).second(22)
    assertTimeEqual assert, actual.shaaZemaniGra(1), moment(date).hour(6).minute(48).second(11)
    assertTimeEqual assert, actual.shaaZemaniGra(2), moment(date).hour(7).minute(59).second(0)
    assertTimeEqual assert, actual.shaaZemaniGra(3), moment(date).hour(9).minute(9).second(50)
    assertTimeEqual assert, actual.shaaZemaniGra(4), moment(date).hour(10).minute(20).second(39)
    assertTimeEqual assert, actual.shaaZemaniGra(5), moment(date).hour(11).minute(31).second(28)
    assertTimeEqual assert, actual.shaaZemaniGra(6), moment(date).hour(12).minute(42).second(17)
    assertTimeEqual assert, actual.shaaZemaniGra(7), moment(date).hour(13).minute(53).second(7)
    assertTimeEqual assert, actual.shaaZemaniGra(8), moment(date).hour(15).minute(3).second(56)
    assertTimeEqual assert, actual.shaaZemaniGra(9), moment(date).hour(16).minute(14).second(45)
    assertTimeEqual assert, actual.shaaZemaniGra(10), moment(date).hour(17).minute(25).second(35)
    assertTimeEqual assert, actual.shaaZemaniGra(11), moment(date).hour(18).minute(36).second(24)
    assertTimeEqual assert, actual.shaaZemaniGra(12), moment(date).hour(19).minute(47).second(13)
    assertTimeEqual assert, actual.magenAbrahamDawn(0), moment(date).hour(4).minute(0).second(21)
    assertTimeEqual assert, actual.earliestTallit(), moment(date).hour(4).minute(40).second(7)
    assertTimeEqual assert, actual.sunrise(), moment(date).hour(5).minute(37).second(22)
    assertTimeEqual assert, actual.chatzot(), moment(date).hour(12).minute(42).second(17)
    assertTimeEqual assert, actual.samuchLeminchaKetana(), moment(date).hour(16).minute(50).second(45)
    assertTimeEqual assert, actual.plag(), moment(date).hour(18).minute(18).second(42)
    assertTimeEqual assert, actual.sunset(), moment(date).hour(19).minute(47).second(13)
    assertTimeEqual assert, actual.setHaKochabimGeonim(), moment(date).hour(20).minute(4).second(9)
    assertTimeEqual assert, actual.setHaKochabim3Stars(), moment(date).hour(20).minute(33).second(39)

$ ->
  zmanimTest()
