#! /usr/bin/env ruby

`#{File.expand_path("#{__FILE__}/..")}/compile`

require 'aws-sdk'
yaml = YAML::load(File.open('aws.yml'))
AWS.config(yaml['credentials'])
BUCKET = AWS::S3.new.buckets[yaml['bucket']]

def upload(f, options={})
  puts "uploading #{f}..."
  BUCKET.objects[f].write(Pathname.new(f), options.merge(:acl => :public_read))
end


Dir['js/*.js'].each { |f| upload(f, :content_type => 'text/javascript' ) }
(Dir['css/*'] + Dir['images/*'] + Dir['*.html']).each { |f| upload(f) }

`git tag -f deployed`
